---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: collab
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: "24.0.3"
    replicaCount: 1
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        hajimari.io/appName: "Nextcloud"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Real-IP, X-Frame-Options, X-Content-Type-Options, X-Forwarded-Proto"
        nginx.ingress.kubernetes.io/proxy-body-size: 10G
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
            - nextcloud.${SECRET_DOMAIN}
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgres.collab.svc.cluster.local:5432
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: db_username
        passwordKey: db_password
    mariadb:
      enabled: false
    postgresql:
      enabled: false
    nextcloud:
      host: nextcloud.${SECRET_DOMAIN}
      username: ${SECRET_NEXTCLOUD_ADMIN_USER}
      password: ${SECRET_NEXTCLOUD_ADMIN_PASSWORD}
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: username
        passwordKey: password
        smtpUsernameKey: smtp_username
        smtpPasswordKey: smtp_password
      mail:
        enabled: true
        fromAddress: no-reply
        domain: ${SECRET_DOMAIN}
        smtp:
          host: ${SECRET_SMTP_HOST}
          secure: tls
          authtype: LOGIN
          port: 587
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 36
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: false
        redis.config.php: false
        smtp.config.php: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'trusted_proxies' =>
              array(
                0 => '${NETWORK_K8S_POD_CIDR}',
                1 => '${NETWORK_K8S_POD_CIDR_V6}',
              )
          );
        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\\OC\\Memcache\\Redis',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => getenv('REDIS_HOST'),
              'port' => getenv('REDIS_HOST_PORT') ?: 6379,
              'password' => getenv('REDIS_HOST_PASSWORD')
            )
          );
        phone_region.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NL',
            'defaultapp' => 'files'
          );
      extraEnv:
        - name: TZ
          value: "${TIMEZONE}"
    redis:
      enabled: true
      usePassword: true
      password: ${SECRET_NEXTCLOUD_REDIS_PASSWORD}
    cronjob:
      annotations: {}
      curlInsecure: false
      enabled: true
      failedJobsHistoryLimit: 5
      image: {}
      schedule: '*/5 * * * *'
      successfulJobsHistoryLimit: 2
    persistence:
      enabled: true
      existingClaim: nextcloud-main
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    metrics:
      enabled: true
      https: false
      image:
        pullPolicy: IfNotPresent
        repository: xperimental/nextcloud-exporter
        tag: 0.5.1
      replicaCount: 1
      service:
        annotations:
          prometheus.io/port: '9205'
          prometheus.io/scrape: 'true'
        labels: {}
        type: ClusterIP
      timeout: 5s
