---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
  namespace: collab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice-documentserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlyoffice-documentserver
    spec:
      # allow container PID to run as root
      securityContext:
        runAsNonRoot: false
      containers:
        - name: documentserver
          # Registry location, container name and version
          image: onlyoffice/documentserver:7.1.1.23
          imagePullPolicy: Always
          resources:
            # CPU & memory allocations
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 1250Mi
          # Readiness & Liveness Health Checks
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthcheck
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 80
            initialDelaySeconds: 200
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          env:
            - name: JWT_ENABLED
              value: "true"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-secret
                  key: secret
          volumeMounts:
            - name: configuration
              mountPath: /etc/nginx/includes/http-common.conf
              readOnly: true
              subPath: http-common.conf
      volumes:
        - name: configuration
          configMap:
            defaultMode: 0666
            name: onlyoffice-config
---
apiVersion: v1
kind: Service
metadata:
  # Create a network endpoint and DNS record within the cluster named documentserver
  name: onlyoffice-documentserver
  namespace: collab
spec:
  ports:
    # Accept traffic sent to port 18080
    - name: http
      port: 80
      targetPort: 80
  selector:
    # Map to all containers with label
    app: onlyoffice-documentserver
