---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: miniflux
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kubegress
      namespace: database
  values:
    image:
      repository: ghcr.io/miniflux/miniflux
      tag: 2.0.37
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
      DATABASE_URL: postgres://miniflux:${SECRET_MINIFLUX_PG_PASSWORD}@miniflux-postgres.default.svc.home-cluster.local/miniflux2?sslmode=disable
      RUN_MIGRATIONS: '1'
      CREATE_ADMIN: '1'
      ADMIN_USERNAME: ${SECRET_MINIFLUX_USER}
      ADMIN_PASSWORD: ${SECRET_MINIFLUX_PASSWORD}

    postgresql:
      enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss-box"
          hajimari.io/appName: "Miniflux"
        hosts:
          - host: "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "rss.${SECRET_DOMAIN}"
